### ISSUE TITLE
Conflicting keyboard shortcuts

### ISSUE THREAD

**Issue by girvo** [flerro/firefox-instasaver#3]
Hey there, love the plugin, it's really well done. Easily the best Instapaper addon for Firefox :+1: 

Unfortunately, there is an issue I've run into; I use Amethyst[0] on OS X as a tiling window manager, and it uses `Alt + Shift` as `mod1` -- which means I can't use the keyboard shortcuts in your extension!

Ideally it would be lovely to have them as a config option (either in the preferences pane or tucked away somewhere) so I can use the extension the way it's meant to be used :) 

Cheers,
Josh

[0] https://github.com/ianyh/Amethyst

**Comment by flerro** [comment]
Sorry, I will not FIX this.
