### ISSUE TITLE
"Problem Storing Login Credentials" Error

### ISSUE THREAD

**Issue by SarahofGaia** [flerro/firefox-instasaver#5]
In Instasaver's settings menu, if I click on "Test login", it says everything's just fine:

![screenshot 2015-01-19 17 38 36---------2](https://cloud.githubusercontent.com/assets/10601870/5805299/7e3fa9b2-a005-11e4-82a3-124081479869.png)

However, as soon as I exit the settings menu by clicking "OK" at the bottom-right, I always get a "Problem Storing Login Credentials" error:

![screenshot 2015-01-19 17 38 49--------2](https://cloud.githubusercontent.com/assets/10601870/5805310/a06dd400-a005-11e4-831d-bd81050ef25b.png)

__________
Troubleshooting Information:

Application Basics
------------------

Name: Firefox
Version: 35.0
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0
Multiprocess Windows: 0/1

Crash Reports for the Last 3 Days
---------------------------------

All Crash Reports (including 1 pending crash in the given time range)

Extensions
----------

Name: Add to feedly
Version: 1.4
Enabled: true
ID: jid1-YZsgHbPHarNxRg@jetpack

Name: Bluhell Firewall
Version: 2.5.0
Enabled: true
ID: {6BB5760D-F97E-421B-AF5B-8457A90C3CED}

Name: Disconnect
Version: 3.14.0
Enabled: true
ID: 2.0@disconnect.me

Name: DuckDuckGo Plus
Version: 0.4.6
Enabled: true
ID: jid1-ZAdIEUB7XOzOJw@jetpack

Name: Flash Video Downloader - YouTube HD Download [4K]
Version: 6.9.3
Enabled: true
ID: artur.dubovoy@gmail.com

Name: FoxClocks
Version: 3.4.14
Enabled: true
ID: {d37dc5d0-431d-44e5-8c91-49419370caa1}

Name: HTTPS-Everywhere
Version: 4.0.2
Enabled: true
ID: https-everywhere@eff.org

Name: Instasaver
Version: 1.7.2
Enabled: true
ID: instasaver@flerro

Name: LastPass
Version: 3.1.1
Enabled: true
ID: support@lastpass.com

Name: NoScript
Version: 2.6.9.11
Enabled: true
ID: {73a6fe31-595d-460b-a920-fcc0f8843232}

Name: Pushbullet
Version: 39
Enabled: true
ID: jid1-BYcQOfYfmBMd9A@jetpack

Name: StumbleUpon
Version: 4.18
Enabled: true
ID: {AE93811A-5C9A-4d34-8462-F7B864FC4696}

Name: Stylish
Version: 2.0.0
Enabled: true
ID: {46551EC9-40F0-4e47-8E18-8E5CF550CFB8}

Name: Tab Counter
Version: 1.9.9
Enabled: true
ID: tabcounter@morac

Name: TheSage one-click lookup
Version: 5.0.4406
Enabled: true
ID: wcapturex@deskperience.com

Name: TinEye Reverse Image Search
Version: 1.1
Enabled: true
ID: tineye@ideeinc.com

Name: HTML5 Notifications
Version: 1.2.2
Enabled: false
ID: html5notifications@paxal.net

Name: Pocket
Version: 3.0.6
Enabled: false
ID: isreaditlater@ideashower.com

Graphics
--------

Adapter Description: Intel(R) Q965/Q963 Express Chipset Family
Adapter Drivers: igdumd64 igdumdx32
Adapter RAM: Unknown
ClearType Parameters: Gamma: 2400 Pixel Structure: R ClearType Level: 100 Enhanced Contrast: 50
Device ID: 0x2992
Direct2D Enabled: Blocked for your graphics driver version.
DirectWrite Enabled: false (6.2.9200.16492)
Driver Date: 9-23-2009
Driver Version: 8.15.10.1930
GPU #2 Active: false
GPU Accelerated Windows: 0/1 Basic (OMTC) Blocked for your graphics driver version.
Subsys ID: 2808103c
Vendor ID: 0x8086
WebGL Renderer: Blocked for your graphics driver version.
windowLayerManagerRemote: true
AzureCanvasBackend: skia
AzureContentBackend: cairo
AzureFallbackCanvasBackend: cairo
AzureSkiaAccelerated: 0

Important Modified Preferences
------------------------------

accessibility.typeaheadfind: true
accessibility.typeaheadfind.flashBar: 0
browser.cache.disk.capacity: 358400
browser.cache.disk.smart_size.first_run: false
browser.cache.disk.smart_size.use_old_max: false
browser.cache.frecency_experiment: 3
browser.places.smartBookmarksVersion: 7
browser.search.useDBForOrder: true
browser.sessionstore.upgradeBackup.latestBuildID: 20150108202552
browser.startup.homepage_override.buildID: 20150108202552
browser.startup.homepage_override.mstone: 35.0
browser.tabs.closeWindowWithLastTab: false
dom.mozApps.used: true
extensions.lastAppVersion: 35.0
media.gmp-gmpopenh264.enabled: true
media.gmp-gmpopenh264.lastUpdate: 1418260905
media.gmp-gmpopenh264.version: 1.1
media.gmp-manager.lastCheck: 1421689010
network.cookie.prefsMigrated: true
places.database.lastMaintenance: 1421689011
places.history.expiration.transient_current_max_pages: 53460
plugin.disable_full_page_plugin_for_types: application/pdf
plugin.importedState: true
plugin.state.flash: 1
plugin.state.npdeployjava: 0
plugin.state.nppdf: 0
plugin.state.npwcx: 1
print.printer_PDFCreator.print_bgcolor: false
print.printer_PDFCreator.print_bgimages: false
print.printer_PDFCreator.print_colorspace:
print.printer_PDFCreator.print_command:
print.printer_PDFCreator.print_downloadfonts: false
print.printer_PDFCreator.print_duplex: 1515870810
print.printer_PDFCreator.print_edge_bottom: 0
print.printer_PDFCreator.print_edge_left: 0
print.printer_PDFCreator.print_edge_right: 0
print.printer_PDFCreator.print_edge_top: 0
print.printer_PDFCreator.print_evenpages: true
print.printer_PDFCreator.print_footercenter:
print.printer_PDFCreator.print_footerleft: &PT
print.printer_PDFCreator.print_footerright: &D
print.printer_PDFCreator.print_headercenter:
print.printer_PDFCreator.print_headerleft: &T
print.printer_PDFCreator.print_headerright: &U
print.printer_PDFCreator.print_in_color: true
print.printer_PDFCreator.print_margin_bottom: 0.5
print.printer_PDFCreator.print_margin_left: 0.5
print.printer_PDFCreator.print_margin_right: 0.5
print.printer_PDFCreator.print_margin_top: 0.5
print.printer_PDFCreator.print_oddpages: true
print.printer_PDFCreator.print_orientation: 0
print.printer_PDFCreator.print_page_delay: 50
print.printer_PDFCreator.print_paper_data: 9
print.printer_PDFCreator.print_paper_height: 11.00
print.printer_PDFCreator.print_paper_name:
print.printer_PDFCreator.print_paper_size_type: 0
print.printer_PDFCreator.print_paper_size_unit: 1
print.printer_PDFCreator.print_paper_width: 8.50
print.printer_PDFCreator.print_plex_name:
print.printer_PDFCreator.print_resolution: 1515870810
print.printer_PDFCreator.print_resolution_name:
print.printer_PDFCreator.print_reversed: false
print.printer_PDFCreator.print_scaling: 1.00
print.printer_PDFCreator.print_shrink_to_fit: true
print.printer_PDFCreator.print_to_file: false
print.printer_PDFCreator.print_unwriteable_margin_bottom: 0
print.printer_PDFCreator.print_unwriteable_margin_left: 0
print.printer_PDFCreator.print_unwriteable_margin_right: 0
print.printer_PDFCreator.print_unwriteable_margin_top: 0
privacy.cpd.offlineApps: true
privacy.cpd.siteSettings: true
privacy.donottrackheader.enabled: true
privacy.sanitize.migrateFx3Prefs: true
privacy.sanitize.timeSpan: 0
storage.vacuum.last.index: 1
storage.vacuum.last.places.sqlite: 1420941501

Important Locked Preferences
----------------------------

JavaScript
----------

Incremental GC: true

Accessibility
-------------

Activated: false
Prevent Accessibility: 0

Library Versions
----------------

NSPR
Expected minimum version: 4.10.7
Version in use: 4.10.7

NSS
Expected minimum version: 3.17.2 Basic ECC
Version in use: 3.17.2 Basic ECC

NSSSMIME
Expected minimum version: 3.17.2 Basic ECC
Version in use: 3.17.2 Basic ECC

NSSSSL
Expected minimum version: 3.17.2 Basic ECC
Version in use: 3.17.2 Basic ECC

NSSUTIL
Expected minimum version: 3.17.2
Version in use: 3.17.2

Experimental Features
---------------------

**Comment by flerro** [comment]
I was able to reproduce the error with Firefox 35.0

I will look into it ASAP. Thanks
